server:
  port: 8888
  servlet:
    context-path: /system
  tomcat:
    uri-encoding: utf-8


spring:
  data:
    mongodb:
      host: 45.62.98.76
      port: 27017
      database: log
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
    timeout: 10000
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/website
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT1FROMDUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    filters: stat,wall,slf4j
    logSlowSql: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
    properties:
      hibernate:
        dialect : com.sunpeng.jpasytem.config.jpa.MySQL5DialectUTF8
    open-in-view: true



  mail:
    #邮箱服务器地址
    host: smtp.qq.com
    #用户名
    username: 121933039@qq.com
    #密码
    password: 123456
    #编码
    default-encoding: UTF-8

#以谁来发送邮件
mail:
  fromMail:
    addr: 121933039@qq.com
logging:
  config: classpath:logging-config.xml

